default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bloggerr_deviser
  username: postgres
  password: reg.edit123
  host: localhost
  port: 5432
  adapter: postgresql

test:
  <<: *default
  database: capybara_test
  username: postgres
  password: reg.edit123
  host: localhost
  port: 5432

production:
  <<: *default
  database: db/production.postgresql
